version: '3.5'

services:
    mysql:
#        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_PASSWORD_FILE: /run/secrets/mysql.pwd
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root.pwd
            MYSQL_USER: ${CFG_USER:?}
            TZ: America/New_York
        hostname: mysql
        image: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}thirdparty/mysql:${MYSQL_VERSION:-5.7.23}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        networks:
            - nagios-net 
        ports:
            - "3306:3306"
        restart: unless-stopped
        secrets:
            - mysql.pwd
            - mysql_root.pwd
        volumes:
            - ./mysql/conf.d:/etc/mysql/conf.d
            - ./mysql/data:/var/lib/mysql
            - ./mysql/loader:/docker-entrypoint-initdb.d
            - ./mysql/log:/var/log


    nagios:
        container_name: nagios
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
#            NAGIOS_GITHUB_CREDENTIALS_FILE: /run/secrets/github.credentials
#            NAGIOS_GITHUB_EMAIL: ${CFG_EMAIL:?}
#            NAGIOS_GITHUB_NAME: ${CFG_NAME:?}
            NAGIOS_PASS_FILE: /run/secrets/nagios.pwd
#            NAGIOS_REPO: github.com/ballab1/DBMS-backup
            NAGIOS_USER: ${CFG_USER:?}
            NAGIOS_URL_HTML_PATH: /nagios
            NCONF_DBHOST: mysql
            NCONF_DBNAME: nconf
            NCONF_DBPASS_FILE: /run/secrets/mysql.pwd
            NCONF_DBUSER: ${CFG_USER:?}
            SUPERVISORD_PASS_FILE: /run/secrets/supervisord.pwd         
            SUPERVISORD_USER: ${CFG_USER:?}
        extra_hosts:
            - \"docker-host:${HOST_IP:?}\"
        hostname: nagios
        image: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/nagios/${NCORE_VERSION:-4.4.5}:${CONTAINER_TAG:-b0ac8613d9cbe611ddf9a9c3eb43a72884d0c95baea7666f34f3ecb77bafc11d}
        links:
            - mysql:mysql
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        networks:
            - nagios-net 
        ports:
            - "25:25"
            - "8001:80"
            - "9001:9001"
        restart: unless-stopped
        secrets:
            - github.credentials
            - mysql.pwd
            - nagios.pwd
            - supervisord.pwd
        volumes:
            - ./nagios/archives:/usr/local/nagios/var/archives
            - ./nagios/config:/usr/local/nagios/share/nconf/output
            - ./nagios/log:/var/log
            - ./nagios/rrd:/usr/local/nagios/var/rrd

    nginx:
        container_name: nginx
        depends_on:
            - nagios
            - phpmyadmin
        environment:
#            NGINX_DEBUG: 1
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
#            PWD_PROTECTED: 'true'
            SUPERVISORD_PASS_FILE: /run/secrets/supervisord.pwd
            SUPERVISORD_USER: ${CFG_USER:?}
            WEB_USER_ID: ${CFG_USER:?}
            WEB_USER_PASS_FILE: /run/secrets/web_user.pwd
        extra_hosts:
            - "ubuntu-s1:10.1.3.11"
            - "ubuntu-s2:10.1.3.12"
            - "ubuntu-s3:10.1.3.6"
            - "ubuntu-s4:10.1.3.10"
            - "ubuntu-s5:10.1.3.14"
            - "ubuntu-s6:10.1.3.15"
            - "ubuntu-s7:10.1.3.16"
            - "ubuntu-s8:10.1.3.17"
        hostname: nginx
        image: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/nginx-proxy/${NGINX_VERSION:-1.16.1}:${CONTAINER_TAG:-cfe0f5ab1bfa6266bc87d8ff68b37f0e87abf4f5ccd16dce2543b33730293185}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        networks:
            - nagios-net 
        ports:
            - "80:80"
            - "443:443"
            - "9005:9001"
        restart: unless-stopped
        secrets:
            - supervisord.pwd
            - web_user.pwd
            - server.crt
            - server.key
            - dhparam.pem
        volumes:
            - ./nginx/log:/var/log
            - ./www:/var/www
            - ./nginx/conf.d:/etc/nginx/proxy.conf

    phpmyadmin:
        container_name: phpmyadmin
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
#            MYSQL_PASSWORD_FILE: /run/secrets/mysql.pwd
#            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root.pwd
#            MYSQL_USER: ${CFG_USER:?}
#            PMA_ABSOLUTE_URI: http://${HOST_IP:?}:8002/phpmyadmin
#            PMA_ARBITRARY: 1
            PMA_HOST: mysql
            PMA_PASSWORD_FILE: /run/secrets/pma.pwd
            PMA_PORT: 3306
            PMA_USER: ${CFG_USER:?}
            PMA_VERBOSE: 1
            SUPERVISORD_PASS_FILE: /run/secrets/supervisord.pwd
            SUPERVISORD_USER: ${CFG_USER:?}
            USER: www-data
        hostname: phpmyadmin
        image: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/phpmyadmin/${PHPMYADMIN_VERSION:-4.9.2}:${CONTAINER_TAG:-2c06e4dff7833eb284c382453a4d281ab115a6211b95f94c310f66b831c6788c}
        links:
            - mysql:mysql
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        networks:
            - nagios-net 
        ports:
            - "8002:80"
            - "9102:9000"
            - "9002:9001"
        restart: unless-stopped
        secrets:
#            - mysql.pwd
#            - mysql_root.pwd
            - pma.pwd
            - supervisord.pwd
        volumes:
            - ./phpmyadmin/log:/var/log
#            - ./phpmyadmin/etc:/etc/phpmyadmin
networks:
   nagios-net:
       ipam:
           config:
               - subnet: 192.168.96.0/24
       name: nagios-container-net

secrets:
   github.credentials:
     file: .secrets/secrets/credentials.github
   mysql.pwd:
     file: .secrets/secrets/bobb.pwd
   mysql_root.pwd:
     file: .secrets/secrets/bobb.pwd
   nagios.pwd:
     file: .secrets/secrets/bobb.pwd
   pma.pwd:
     file: .secrets/secrets/bobb.pwd
#   github.token:
#     file: .secrets/secrets/hubot_token.github
   supervisord.pwd:      
     file: .secrets/secrets/bobb.pwd
   web_user.pwd:
     file: .secrets/secrets/bobb.pwd
   server.crt:
     file: .secrets/ssl/server.crt
   server.key:
     file: .secrets/ssl/server.key
   dhparam.pem:
     file: .secrets/ssl/dhparam.pem
